baseURL = "https://matnoren.github.io/"
languageCode = "es"
title = "0xmatnoren"
theme = "hello-friend-ng"

[pagination]
pagerSize = 10

[params]
homeSubtitle = "frontend • linux • pentesting"
defaultTheme = "dark"
enableThemeToggle = true

[params.logo]
logoText = "0xmatnoren"
logoHomeLink = "/"

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts"

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects"

[[menu.main]]
identifier = "about"
name = "about"
url = "/about"
